FROM python:3.12.3

ENV DJANGO_SETTINGS_MODULE=core.settings.localhost
ENV DEBUG=False

WORKDIR /usr/srv/app

COPY . /usr/srv/app

RUN apt update \ 
    && apt upgrade -y \ 
    && apt install libpq-dev gettext\ 
    && pip install --no-cache-dir -r ./requirements.txt \ 
    && ./manage.py collectstatic --noinput

ENTRYPOINT ./scripts/docker.entrypoint.sh

EXPOSE 8000