version: "3.7"

services:

  postgres:
    image: postgres
    container_name: postgres
    hostname: postgres
    network_mode: bridge
    restart: "always"
    environment: 
      POSTGRES_PASSWORD: postgres
      POSTGRES_USER: postgres
      POSTGRES_DB: app
      PGDATA: /var/lib/postgresql/data/pgdata
    volumes: 
      - ./database/postgresql/data:/var/lib/postgresql/data
    ports: 
      - "5432"

  app:
    build:
      context: ../
      dockerfile: ./docker/dockerfile
    container_name: app
    hostname: app
    network_mode: bridge
    restart: always
    environment:
      DJANGO_SETTINGS_MODULE: 'core.settings.docker'
      DEBUG: 'False'
      SECRET_KEY: ''
    volumes: 
      - ./database:/usr/srv/app/database
    ports:
    - 8000:8000
    depends_on:
      - postgres
      