version: "3.9"

services:

  postgres:
    image: postgres
    container_name: postgres
    hostname: postgres
    restart: "always"
    environment: 
      POSTGRES_PASSWORD: postgres
      POSTGRES_USER: postgres
      POSTGRES_DB: postgres
      PGDATA: /var/lib/postgresql/data/pgdata
    volumes: 
      - ../databases/postgresql/data:/var/lib/postgresql/data
    ports: 
      - "5432:5432"

  app:
    build:
      context: ../
      dockerfile: ./docker/dockerfile
    container_name: app
    hostname: app
    restart: always
    environment:
      DJANGO_SETTINGS_MODULE: 'core.settings.docker'
      DATABASE_NAME: postgres
      DATABASE_USER: postgres
      DATABASE_PASSWORD: postgres
      DATABASE_HOST: postgres
      DATABASE_PORT: 5432
    volumes: 
      - ../databases:/usr/srv/app/database
    ports:
      - 8080:8000
    depends_on:
      - postgres
